# Generated by Django 2.2 on 2022-04-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_time', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=250, unique=True)),
                ('numero_telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=15)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Equipe')),
            ],
        ),
    ]
