# Generated by Django 4.0.3 on 2022-04-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220419_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='user_fk',
        ),
        migrations.AddField(
            model_name='user',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.equipe', unique=True),
        ),
    ]
