# Generated by Django 4.0.3 on 2022-04-20 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_equipe_user_fk_user_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=150)),
                ('numero_da_casa', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='endereco_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.endereco'),
        ),
    ]
